name: Request a guide
description: Use this form to request new guides for any new trading partner, and we’ll
  add them to the catalog for free. If you provide us with the PDFs, we typically
  can add them to the catalog within 48 hours.
title: "[GUIDE] Company name"
body:
  - type: input
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
  - type: input
    attributes:
      label: Company name
      placeholder: Tell us what's the name of the company you'd like us to add to the EDI Guide Catalog
  - type: input
    attributes:
      label: EDI Specifications
      description: Please provide a link to the EDI Specs or upload the PDFs
  - type: textarea
    attributes:
      label: Details
      description: If you have any questions or context to add, please let us know
